build_from:
  aarch64: "docker.io/patdelapampa/pve-qdevice:latest"
  amd64: "docker.io/patdelapampa/pve-qdevice:latest"
  armhf: "docker.io/patdelapampa/pve-qdevice:latest"
  armv7: "docker.io/patdelapampa/pve-qdevice:latest"
  i386: "docker.io/patdelapampa/pve-qdevice:latest"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Example add-on"
  org.opencontainers.image.description: "Example add-on to use as a blueprint for new add-ons."
  org.opencontainers.image.source: "https://github.com/home-assistant/addons-example"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
