name: "qdevice"
description: "Qdevice Quorum"
version: "1.0.0"
slug: "hello_world"
environment:
init: false
ports:
  2222/tcp: "22"
  5404/udp: "5404"
  5405/udp: "5405"
  5406/udp: "5406"
environment:
  ROOT_PASSWORD: changeMe!    # Set the root user password. If not set, the default password is 'qdevice'
map:
  - type: data
    path: /etc/corosync
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
image: "Dockerfile.{arch}"
